version: "3.9"

services:
#  zerotier:
#    image: dec0dos/zerotier-controller:latest
#    container_name: zu-controller
#    build:
#      context: .
#      dockerfile: ./docker/zerotier/Dockerfile
#    restart: unless-stopped
#    volumes:
#      - controller_data:/var/lib/zerotier-one
#    expose:
#      - "9993/tcp"
#    ports:
#      - "9993:9993/udp"
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: "no"
  zero-ui:
    image: styliteag/zero-ui-userportal:latest
    container_name: zero-ui-userportal
    build:
      context: .
      dockerfile: ./docker/zero-ui/Dockerfile
    restart: unless-stopped
    depends_on:
     - docker-host
    #  - zerotier
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      #- ./controller_data:/var/lib/zerotier-one
      - /var/lib/zerotier-one:/var/lib/zerotier-one
      - ./zero-ui_data:/app/config
    environment:
      - ZU_CONTROLLER_ENDPOINT=http://docker-host:9993/
      - ZU_DEFAULT_USERNAME=stylite
      - ZU_DEFAULT_PASSWORD=REDACTED_PASSWORD
      #- FLASK_ENV=development
    #expose:
    #  - "80"
    restart: "no"
  https-proxy:
    image: caddy:latest
    container_name: zu-https-proxy
    restart: unless-stopped
    depends_on:
      - zero-ui
    command: caddy reverse-proxy --from zt.stylite-live.net --to zero-ui:80
    volumes:
      - caddy_data:/data
    ports:
      - "80:80"
      - "443:443"
    restart: "no"
volumes:
  zero-ui_data:
  controller_data:
  caddy_data:
